package com.otr.soap;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development
//
// ---------------------------------------------------

public interface IServiceEvents
{
	public void Starting();

	public void Completed(OperationResult result);
}
