package com.otr.soap;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development
//
// ---------------------------------------------------

import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ModelRunProcess extends AttributeContainer implements KvmSerializable
{

	public String				serviceType;

	public DataRow				ParamValues		= new DataRow();

	public Integer				AD_Process_ID	= 0;

	public Integer				AD_Menu_ID		= 0;

	public Integer				AD_Record_ID	= 0;

	public String				DocAction;
	private transient Object	__source;

	public void loadFromSoap(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
	{
		if (paramObj == null)
			return;
		AttributeContainer inObj = (AttributeContainer) paramObj;
		__source = inObj;
		if (inObj instanceof SoapObject)
		{
			SoapObject soapObject = (SoapObject) inObj;
			int size = soapObject.getPropertyCount();
			for (int i0 = 0; i0 < size; i0++)
			{
				PropertyInfo info = soapObject.getPropertyInfo(i0);
				if (!loadProperty(info, soapObject, __envelope))
				{
				}
			}
		}
		if (inObj.hasAttribute("AD_Process_ID"))
		{
			Object j = inObj.getAttribute("AD_Process_ID");
			if (j != null)
			{
				AD_Process_ID = Integer.parseInt(j.toString());
			}
		}
		if (inObj.hasAttribute("AD_Menu_ID"))
		{
			Object j = inObj.getAttribute("AD_Menu_ID");
			if (j != null)
			{
				AD_Menu_ID = Integer.parseInt(j.toString());
			}
		}
		if (inObj.hasAttribute("AD_Record_ID"))
		{
			Object j = inObj.getAttribute("AD_Record_ID");
			if (j != null)
			{
				AD_Record_ID = Integer.parseInt(j.toString());
			}
		}
		if (inObj.hasAttribute("DocAction"))
		{
			Object j = inObj.getAttribute("DocAction");
			if (j != null)
			{
				DocAction = j.toString();
			}
		}

	}

	protected boolean loadProperty(PropertyInfo info, SoapObject soapObject,
			ExtendedSoapSerializationEnvelope __envelope)
	{
		Object obj = info.getValue();
		if (info.name.equals("serviceType"))
		{
			if (obj != null)
			{
				if (obj.getClass().equals(SoapPrimitive.class))
				{
					SoapPrimitive j = (SoapPrimitive) obj;
					if (j.toString() != null)
					{
						this.serviceType = j.toString();
					}
				}
				else if (obj instanceof String)
				{
					this.serviceType = (String) obj;
				}
			}
			return true;
		}
		if (info.name.equals("ParamValues"))
		{
			if (obj != null)
			{
				Object j = obj;
				this.ParamValues = (DataRow) __envelope.get(j, DataRow.class, false);
			}
			return true;
		}
		return false;
	}

	public Object getOriginalXmlSource()
	{
		return __source;
	}

	@Override
	public Object getProperty(int propertyIndex)
	{
		// !!!!! If you have a compilation error here then you are using old
		// version of ksoap2 library. Please upgrade to the latest version.
		// !!!!! You can find a correct version in Lib folder from generated zip
		// file!!!!!
		if (propertyIndex == 0)
		{
			return serviceType;
		}
		if (propertyIndex == 1)
		{
			return ParamValues;
		}
		return null;
	}

	@Override
	public int getPropertyCount()
	{
		return 2;
	}

	@Override
	public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
	{
		if (propertyIndex == 0)
		{
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "serviceType";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
		if (propertyIndex == 1)
		{
			info.type = PropertyInfo.VECTOR_CLASS;
			info.name = "ParamValues";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
	}

	@Override
	public void setProperty(int arg0, Object arg1)
	{
	}

	@Override
	public int getAttributeCount()
	{
		return 4;
	}

	@Override
	public void getAttributeInfo(int index, AttributeInfo info)
	{
		if (index == 0)
		{
			info.name = "AD_Process_ID";
			info.namespace = "";
			if (this.AD_Process_ID != null)
			{
				info.setValue(this.AD_Process_ID);
			}

		}
		if (index == 1)
		{
			info.name = "AD_Menu_ID";
			info.namespace = "";
			if (this.AD_Menu_ID != null)
			{
				info.setValue(this.AD_Menu_ID);
			}

		}
		if (index == 2)
		{
			info.name = "AD_Record_ID";
			info.namespace = "";
			if (this.AD_Record_ID != null)
			{
				info.setValue(this.AD_Record_ID);
			}

		}
		if (index == 3)
		{
			info.name = "DocAction";
			info.namespace = "";
			if (this.DocAction != null)
			{
				info.setValue(this.DocAction);
			}

		}
	}

	@Override
	public void getAttribute(int i, AttributeInfo attributeInfo)
	{

	}

	@Override
	public void setAttribute(AttributeInfo attributeInfo)
	{

	}
}
