package com.otr.soap;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development
//
// ---------------------------------------------------

import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class ModelRunProcessRequest extends AttributeContainer implements KvmSerializable
{

	public ModelRunProcess		ModelRunProcess;

	public ADLoginRequest		ADLoginRequest;
	private transient Object	__source;

	public void loadFromSoap(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
	{
		if (paramObj == null)
			return;
		AttributeContainer inObj = (AttributeContainer) paramObj;
		__source = inObj;
		if (inObj instanceof SoapObject)
		{
			SoapObject soapObject = (SoapObject) inObj;
			int size = soapObject.getPropertyCount();
			for (int i0 = 0; i0 < size; i0++)
			{
				PropertyInfo info = soapObject.getPropertyInfo(i0);
				if (!loadProperty(info, soapObject, __envelope))
				{
				}
			}
		}

	}

	protected boolean loadProperty(PropertyInfo info, SoapObject soapObject,
			ExtendedSoapSerializationEnvelope __envelope)
	{
		Object obj = info.getValue();
		if (info.name.equals("ModelRunProcess"))
		{
			if (obj != null)
			{
				Object j = obj;
				this.ModelRunProcess = (ModelRunProcess) __envelope.get(j, ModelRunProcess.class, false);
			}
			return true;
		}
		if (info.name.equals("ADLoginRequest"))
		{
			if (obj != null)
			{
				Object j = obj;
				this.ADLoginRequest = (ADLoginRequest) __envelope.get(j, ADLoginRequest.class, false);
			}
			return true;
		}
		return false;
	}

	public Object getOriginalXmlSource()
	{
		return __source;
	}

	@Override
	public Object getProperty(int propertyIndex)
	{
		// !!!!! If you have a compilation error here then you are using old
		// version of ksoap2 library. Please upgrade to the latest version.
		// !!!!! You can find a correct version in Lib folder from generated zip
		// file!!!!!
		if (propertyIndex == 0)
		{
			return ModelRunProcess;
		}
		if (propertyIndex == 1)
		{
			return ADLoginRequest;
		}
		return null;
	}

	@Override
	public int getPropertyCount()
	{
		return 2;
	}

	@Override
	public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
	{
		if (propertyIndex == 0)
		{
			info.type = ModelRunProcess.class;
			info.name = "ModelRunProcess";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
		if (propertyIndex == 1)
		{
			info.type = ADLoginRequest.class;
			info.name = "ADLoginRequest";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
	}

	@Override
	public void setProperty(int arg0, Object arg1)
	{
	}

}
