package com.otr.soap;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development
//
// ---------------------------------------------------

import java.util.List;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class ModelADServiceSoapBinding
{
	interface GHEIWcfMethod
	{
		ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

		Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
	}

	private String				url		= "";

	int							timeOut	= 60000;
	public List<HeaderProperty>	httpHeaders;
	public boolean				enableLogging;

	IServiceEvents				callback;

	public ModelADServiceSoapBinding()
	{
	}

	public ModelADServiceSoapBinding(IServiceEvents callback, String url)
	{
		this.callback = callback;
		this.url = url;
	}

	public ModelADServiceSoapBinding(IServiceEvents callback, String url, int timeOut)
	{
		this.callback = callback;
		this.url = url;
		this.timeOut = timeOut;
	}

	protected org.ksoap2.transport.Transport createTransport()
	{
		try
		{
			java.net.URI uri = new java.net.URI(url);
			if (uri.getScheme().equalsIgnoreCase("https"))
			{
				int port = uri.getPort() > 0 ? uri.getPort() : 443;
				return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(),
						timeOut);
			}
			else
			{
				return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url, timeOut);
			}

		}
		catch (java.net.URISyntaxException e)
		{
		}
		return null;
	}

	protected ExtendedSoapSerializationEnvelope createEnvelope()
	{
		ExtendedSoapSerializationEnvelope envelope = new ExtendedSoapSerializationEnvelope(
				ExtendedSoapSerializationEnvelope.VER11);
		return envelope;
	}

	protected List sendRequest(String methodName, ExtendedSoapSerializationEnvelope envelope,
			org.ksoap2.transport.Transport transport,
			com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws Exception
	{
		if (transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)
		{
			return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) transport).call(methodName, envelope,
					httpHeaders, null, profile);
		}
		else
		{
			return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE) transport).call(methodName, envelope,
					httpHeaders, null, profile);
		}
	}

	Object getResult(Class destObj, Object source, String resultName, ExtendedSoapSerializationEnvelope __envelope)
			throws Exception
	{
		if (source == null)
		{
			return null;
		}
		if (source instanceof SoapPrimitive)
		{
			SoapPrimitive soap = (SoapPrimitive) source;
			if (soap.getName().equals(resultName))
			{
				Object instance = __envelope.get(source, destObj, false);
				return instance;
			}
		}
		else
		{
			SoapObject soap = (SoapObject) source;
			if (soap.hasProperty(resultName))
			{
				Object j = soap.getProperty(resultName);
				if (j == null)
				{
					return null;
				}
				Object instance = __envelope.get(j, destObj, false);
				return instance;
			}
			else if (soap.getName().equals(resultName))
			{
				Object instance = __envelope.get(source, destObj, false);
				return instance;
			}
		}

		return null;
	}

	public StandardResponse createUpdateData(final ModelCRUDRequest ModelCRUDRequest) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (StandardResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelCRUDRequest",
						new ModelCRUDRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "createUpdateData");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelCRUDRequest";
				__info.type = ModelCRUDRequest.class;
				__info.setValue(ModelCRUDRequest);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (StandardResponse) getResult(StandardResponse.class, __result, "StandardResponse", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<StandardResponse>> createUpdateDataAsync(
			final ModelCRUDRequest ModelCRUDRequest)
	{
		return executeAsync(new Functions.IFunc<StandardResponse>() {
			public StandardResponse Func() throws Exception
			{
				return createUpdateData(ModelCRUDRequest);
			}
		}, "createUpdateData");
	}

	public StandardResponse runProcessTrx(final ModelRunProcessRequest ModelRunProcessRequest) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (StandardResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelRunProcessRequest",
						new ModelRunProcessRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "runProcessTrx");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelRunProcessRequest";
				__info.type = ModelRunProcessRequest.class;
				__info.setValue(ModelRunProcessRequest);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (StandardResponse) getResult(StandardResponse.class, __result, "StandardResponse", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<StandardResponse>> runProcessTrxAsync(
			final ModelRunProcessRequest ModelRunProcessRequest)
	{
		return executeAsync(new Functions.IFunc<StandardResponse>() {
			public StandardResponse Func() throws Exception
			{
				return runProcessTrx(ModelRunProcessRequest);
			}
		}, "runProcessTrx");
	}

	public StandardResponse setDocAction(final ModelSetDocActionRequest ModelSetDocActionRequest) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (StandardResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelSetDocActionRequest",
						new ModelSetDocActionRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "setDocAction");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelSetDocActionRequest";
				__info.type = ModelSetDocActionRequest.class;
				__info.setValue(ModelSetDocActionRequest);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (StandardResponse) getResult(StandardResponse.class, __result, "StandardResponse", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<StandardResponse>> setDocActionAsync(
			final ModelSetDocActionRequest ModelSetDocActionRequest)
	{
		return executeAsync(new Functions.IFunc<StandardResponse>() {
			public StandardResponse Func() throws Exception
			{
				return setDocAction(ModelSetDocActionRequest);
			}
		}, "setDocAction");
	}

	public StandardResponse createData(final ModelCRUDRequest ModelCRUDRequest) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (StandardResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelCRUDRequest",
						new ModelCRUDRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "createData");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelCRUDRequest";
				__info.type = ModelCRUDRequest.class;
				__info.setValue(ModelCRUDRequest);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (StandardResponse) getResult(StandardResponse.class, __result, "StandardResponse", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<StandardResponse>> createDataAsync(
			final ModelCRUDRequest ModelCRUDRequest)
	{
		return executeAsync(new Functions.IFunc<StandardResponse>() {
			public StandardResponse Func() throws Exception
			{
				return createData(ModelCRUDRequest);
			}
		}, "createData");
	}

	public StandardResponse deleteData(final ModelCRUDRequest ModelCRUDRequest) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (StandardResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelCRUDRequest",
						new ModelCRUDRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "deleteData");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelCRUDRequest";
				__info.type = ModelCRUDRequest.class;
				__info.setValue(ModelCRUDRequest);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (StandardResponse) getResult(StandardResponse.class, __result, "StandardResponse", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<StandardResponse>> deleteDataAsync(
			final ModelCRUDRequest ModelCRUDRequest)
	{
		return executeAsync(new Functions.IFunc<StandardResponse>() {
			public StandardResponse Func() throws Exception
			{
				return deleteData(ModelCRUDRequest);
			}
		}, "deleteData");
	}

	public WindowTabData readData(final ModelCRUDRequest request) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (WindowTabData) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelCRUDRequest",
						new ModelRunProcessRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "readData");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelCRUDRequest";
				__info.type = ModelCRUDRequest.class;
				__info.setValue(request);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (WindowTabData) getResult(WindowTabData.class, __result, "WindowTabData", __envelope);
			}
		}, "", __profile);

	}

	/**
	 * This method is available in Premium account only. To test if generated
	 * classes work correctly with your webservice, please use different method.
	 * Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits
	 * of Premium account.
	 */
	public android.os.AsyncTask<Void, Void, OperationResult<WindowTabData>> readDataAsync(
			final ModelCRUDRequest request)
	{
		return executeAsync(new Functions.IFunc<WindowTabData>() {
			public WindowTabData Func() throws Exception
			{
				return readData(request);
			}
		}, "readData");
	}

	public WindowTabData getList(final ModelGetListRequest request) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (WindowTabData) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelGetListRequest",
						new ModelRunProcessRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "getList");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelGetListRequest";
				__info.type = ModelRunProcessRequest.class;
				__info.setValue(request);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (WindowTabData) getResult(WindowTabData.class, __result, "WindowTabData", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<WindowTabData>> getListAsync(
			final ModelGetListRequest request)
	{
		return executeAsync(new Functions.IFunc<WindowTabData>() {
			public WindowTabData Func() throws Exception
			{
				return getList(request);
			}
		}, "getList");
	}

	public RunProcessResponse runProcess(final ModelRunProcessRequest request) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (RunProcessResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelRunProcessRequest",
						new ModelRunProcessRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "runProcess");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelRunProcessRequest";
				__info.type = ModelRunProcessRequest.class;
				__info.setValue(request);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (RunProcessResponse) getResult(RunProcessResponse.class, __result, "RunProcessResponse",
						__envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<RunProcessResponse>> runProcessAsync(
			final ModelRunProcessRequest request)
	{
		return executeAsync(new Functions.IFunc<RunProcessResponse>() {
			public RunProcessResponse Func() throws Exception
			{
				return runProcess(request);
			}
		}, "runProcess");
	}

	public StandardResponse updateData(final ModelCRUDRequest request) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (StandardResponse) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelCRUDRequest",
						new ModelCRUDRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "updateData");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelCRUDRequest";
				__info.type = ModelCRUDRequest.class;
				__info.setValue(request);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (StandardResponse) getResult(StandardResponse.class, __result, "StandardResponse", __envelope);
			}
		}, "", __profile);
	}

	public android.os.AsyncTask<Void, Void, OperationResult<StandardResponse>> updateDataAsync(
			final ModelCRUDRequest request)
	{
		return executeAsync(new Functions.IFunc<StandardResponse>() {
			public StandardResponse Func() throws Exception
			{
				return updateData(request);
			}
		}, "updateData");
	}

	public WindowTabData queryData(final ModelCRUDRequest request) throws Exception
	{
		com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
		return (WindowTabData) execute(new GHEIWcfMethod() {
			@Override
			public ExtendedSoapSerializationEnvelope CreateSoapEnvelope()
			{
				ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
				__envelope.addMapping("http://idempiere.org/ADInterface/1_0", "ModelCRUDRequest",
						new ModelCRUDRequest().getClass());
				SoapObject __soapReq = new SoapObject("http://idempiere.org/ADInterface/1_0", "queryData");
				__envelope.setOutputSoapObject(__soapReq);

				PropertyInfo __info = null;
				__info = new PropertyInfo();
				__info.namespace = "http://idempiere.org/ADInterface/1_0";
				__info.name = "ModelCRUDRequest";
				__info.type = ModelCRUDRequest.class;
				__info.setValue(request);
				__soapReq.addProperty(__info);
				return __envelope;
			}

			@Override
			public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object __result) throws Exception
			{
				return (WindowTabData) getResult(WindowTabData.class, __result, "WindowTabData", __envelope);
			}
		}, "", __profile);
	}

	/**
	 * This method is available in Premium account only. To test if generated
	 * classes work correctly with your webservice, please use different method.
	 * Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits
	 * of Premium account.
	 */
	public android.os.AsyncTask<Void, Void, OperationResult<WindowTabData>> queryDataAsync(
			final ModelCRUDRequest request)
	{
		return executeAsync(new Functions.IFunc<WindowTabData>() {
			public WindowTabData Func() throws Exception
			{
				return queryData(request);
			}
		}, "queryData");
	}

	protected Object execute(GHEIWcfMethod wcfMethod, String methodName,
			com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws Exception
	{
		org.ksoap2.transport.Transport __httpTransport = createTransport();
		__httpTransport.debug = enableLogging;
		ExtendedSoapSerializationEnvelope __envelope = wcfMethod.CreateSoapEnvelope();
		try
		{
			sendRequest(methodName, __envelope, __httpTransport, profile);

		}
		finally
		{
			if (__httpTransport.debug)
			{
				if (__httpTransport.requestDump != null)
				{
					android.util.Log.i("requestDump", __httpTransport.requestDump);

				}
				if (__httpTransport.responseDump != null)
				{
					android.util.Log.i("responseDump", __httpTransport.responseDump);
				}
			}
		}
		Object __retObj = __envelope.bodyIn;
		if (__retObj instanceof org.ksoap2.SoapFault)
		{
			org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault) __retObj;
			throw convertToException(__fault, __envelope);
		}
		else
		{
			return wcfMethod.ProcessResult(__envelope, __retObj);
		}
	}

	protected <T> android.os.AsyncTask<Void, Void, OperationResult<T>> executeAsync(final Functions.IFunc<T> func,
			final String methodName)
	{
		return new android.os.AsyncTask<Void, Void, OperationResult<T>>() {
			@Override
			protected void onPreExecute()
			{
				callback.Starting();
			};

			@Override
			protected OperationResult<T> doInBackground(Void... params)
			{
				OperationResult<T> result = new OperationResult<T>();
				try
				{
					result.MethodName = methodName;
					result.Result = func.Func();
				}
				catch (Exception ex)
				{
					ex.printStackTrace();
					result.Exception = ex;
				}
				return result;
			}

			@Override
			protected void onPostExecute(OperationResult<T> result)
			{
				callback.Completed(result);
			}
		}.execute();
	}

	protected Exception convertToException(org.ksoap2.SoapFault fault, ExtendedSoapSerializationEnvelope envelope)
	{
		org.ksoap2.SoapFault newException = fault;

		return newException;
	}
}
