package com.otr.soap;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development
//
// ---------------------------------------------------

public class OperationResult<T>
{
	public java.lang.Exception	Exception;
	public T					Result;
	public Object				Tag;
	public String				MethodName;
}
