package com.otr.soap;

// ----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development
//
// ---------------------------------------------------

import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class StandardResponse extends AttributeContainer implements KvmSerializable
{
	public String					Error;

	public ArrayList<OutputFields>	outputFields	= new ArrayList<OutputFields>();

	public RunProcessResponse		RunProcessResponse;

	public WindowTabData			WindowTabData;

	public ADLoginResponse			ADLoginResponse;

	public Boolean					IsError			= false;

	public Boolean					IsRolledBack	= false;

	public Integer					RecordID		= 0;
	private transient Object		__source;

	public void loadFromSoap(Object paramObj, ExtendedSoapSerializationEnvelope __envelope)
	{
		if (paramObj == null)
			return;
		AttributeContainer inObj = (AttributeContainer) paramObj;
		__source = inObj;
		if (inObj instanceof SoapObject)
		{
			SoapObject soapObject = (SoapObject) inObj;
			int size = soapObject.getPropertyCount();
			for (int i0 = 0; i0 < size; i0++)
			{
				PropertyInfo info = soapObject.getPropertyInfo(i0);
				if (!loadProperty(info, soapObject, __envelope))
				{
				}
			}
		}
		if (inObj.hasAttribute("IsError"))
		{
			Object j = inObj.getAttribute("IsError");
			if (j != null)
			{
				IsError = new Boolean(j.toString());
			}
		}
		if (inObj.hasAttribute("IsRolledBack"))
		{
			Object j = inObj.getAttribute("IsRolledBack");
			if (j != null)
			{
				IsRolledBack = new Boolean(j.toString());
			}
		}
		if (inObj.hasAttribute("RecordID"))
		{
			Object j = inObj.getAttribute("RecordID");
			if (j != null)
			{
				RecordID = Integer.parseInt(j.toString());
			}
		}

	}

	protected boolean loadProperty(PropertyInfo info, SoapObject soapObject,
			ExtendedSoapSerializationEnvelope __envelope)
	{
		Object obj = info.getValue();
		if (info.name.equals("Error"))
		{
			if (obj != null)
			{
				if (obj.getClass().equals(SoapPrimitive.class))
				{
					SoapPrimitive j = (SoapPrimitive) obj;
					if (j.toString() != null)
					{
						this.Error = j.toString();
					}
				}
				else if (obj instanceof String)
				{
					this.Error = (String) obj;
				}
			}
			return true;
		}
		if (info.name.equals("outputFields"))
		{
			if (obj != null)
			{
				if (this.outputFields == null)
				{
					this.outputFields = new ArrayList<OutputFields>();
				}
				Object j = obj;
				OutputFields j1 = (OutputFields) __envelope.get(j, OutputFields.class, false);
				this.outputFields.add(j1);
			}
			return true;
		}
		if (info.name.equals("RunProcessResponse"))
		{
			if (obj != null)
			{
				Object j = obj;
				this.RunProcessResponse = (RunProcessResponse) __envelope.get(j, RunProcessResponse.class, false);
			}
			return true;
		}
		if (info.name.equals("WindowTabData"))
		{
			if (obj != null)
			{
				Object j = obj;
				this.WindowTabData = (WindowTabData) __envelope.get(j, WindowTabData.class, false);
			}
			return true;
		}
		if (info.name.equals("ADLoginResponse"))
		{
			if (obj != null)
			{
				Object j = obj;
				this.ADLoginResponse = (ADLoginResponse) __envelope.get(j, ADLoginResponse.class, false);
			}
			return true;
		}
		return false;
	}

	public Object getOriginalXmlSource()
	{
		return __source;
	}

	@Override
	public Object getProperty(int propertyIndex)
	{
		// !!!!! If you have a compilation error here then you are using old
		// version of ksoap2 library. Please upgrade to the latest version.
		// !!!!! You can find a correct version in Lib folder from generated zip
		// file!!!!!
		if (propertyIndex == 0)
		{
			return this.Error != null ? this.Error : SoapPrimitive.NullSkip;
		}
		if (propertyIndex >= 1 && propertyIndex < 1 + this.outputFields.size())
		{
			Object outputFields = this.outputFields.get(propertyIndex - (1));
			return outputFields != null ? outputFields : SoapPrimitive.NullNilElement;
		}
		if (propertyIndex == 1 + this.outputFields.size())
		{
			return this.RunProcessResponse != null ? this.RunProcessResponse : SoapPrimitive.NullSkip;
		}
		if (propertyIndex == 2 + this.outputFields.size())
		{
			return this.WindowTabData != null ? this.WindowTabData : SoapPrimitive.NullSkip;
		}
		if (propertyIndex == 3 + this.outputFields.size())
		{
			return this.ADLoginResponse != null ? this.ADLoginResponse : SoapPrimitive.NullSkip;
		}
		return null;
	}

	@Override
	public int getPropertyCount()
	{
		return 4 + outputFields.size();
	}

	@Override
	public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
	{
		if (propertyIndex == 0)
		{
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "Error";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
		if (propertyIndex >= 1 && propertyIndex < 1 + this.outputFields.size())
		{
			info.type = PropertyInfo.VECTOR_CLASS;
			info.name = "outputFields";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
		if (propertyIndex == 1 + this.outputFields.size())
		{
			info.type = RunProcessResponse.class;
			info.name = "RunProcessResponse";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
		if (propertyIndex == 2 + this.outputFields.size())
		{
			info.type = WindowTabData.class;
			info.name = "WindowTabData";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
		if (propertyIndex == 3 + this.outputFields.size())
		{
			info.type = ADLoginResponse.class;
			info.name = "ADLoginResponse";
			info.namespace = "http://idempiere.org/ADInterface/1_0";
		}
	}

	@Override
	public void setProperty(int arg0, Object arg1)
	{
	}

	@Override
	public int getAttributeCount()
	{
		return 3;
	}

	@Override
	public void getAttributeInfo(int index, AttributeInfo info)
	{
		if (index == 0)
		{
			info.name = "IsError";
			info.namespace = "";
			if (this.IsError != null)
			{
				info.setValue(this.IsError);
			}

		}
		if (index == 1)
		{
			info.name = "IsRolledBack";
			info.namespace = "";
			if (this.IsRolledBack != null)
			{
				info.setValue(this.IsRolledBack);
			}

		}
		if (index == 2)
		{
			info.name = "RecordID";
			info.namespace = "";
			if (this.RecordID != null)
			{
				info.setValue(this.RecordID);
			}

		}
	}

	@Override
	public void getAttribute(int i, AttributeInfo attributeInfo)
	{

	}

	@Override
	public void setAttribute(AttributeInfo attributeInfo)
	{

	}
}
